### ISSUE TITLE
Request: Mount Debrid

### ISSUE THREAD

**Issue by JonnySiHI** [RouxieLM/RDAutomation#4]
Hey, nice work!,

Anychance that mounting the webdav folder and/for symlinking would be possible?

Cheers
Jonny5

**Comment by RouxieLM** [comment]
Hello, thank you !

Could give me an example of how you want to use WebDAV and symlinks with RDAutomation ?

I didn't think about a feature like that but it could be interesting.

**Comment by JonnySiHI** [comment]
For example, the WebDAV folder would be mounted and then those links would be symlinked into another folder for Sonarr/Radarr to rename appropriately.

Or have RDAutomation rename the files in the folder with the symbolic links.

Hope that makes sense! :)

**Comment by RouxieLM** [comment]
Hello,

Ok I see, well, it is not planned. For now, the only aim is to download a batch of files from a torrent and put them in the right location.

All the things i'm working on are in the "What I'm working on" section in the Readme.

The two main goals right now are :
1. Support for multiple torrent sites, at least 2. I'm aiming to add Nyaa.si because TPB is not so good when it comes to anime.
2. WebUI. The user can open his phone or any device, select what he wants and have his content on his server automatically without having to go on his PC. And this webUI will probably come in a container.

I'll keep this in a corner of my head in case I want to implement something similar in the future, especially paired with a webUI.

Have a nice week !

**Comment by RouxieLM** [comment]
Closing, not planned

**Comment by dinjojo** [comment]
Maybe add support for torrentio and that would take care of 90% of all needs of tracker.
